export type Service = {
  slug: string; number: string; title: string; category: string; summary: string;
  deliverables: string[]; useCases: string[]; icon: string;
};

export const services: Service[] = [
  { slug: "turning-movement-counts", number: "01", title: "Traffic Turning Movement Counts (TMC)", category: "Intersection", icon: "Route", summary: "Classified vehicle, pedestrian and cyclist movements at signalised or unsignalised intersections.", deliverables: ["Movement tables by approach and interval", "Turning-movement diagrams", "Peak-hour and PHF summaries"], useCases: ["Junction modelling", "Transport assessments", "Signal reviews"] },
  { slug: "vehicle-classification", number: "02", title: "Vehicle Classification Surveys", category: "Traffic", icon: "Car", summary: "Traffic composition by vehicle type using DfT, FHWA or a client-approved classification scheme.", deliverables: ["Class-wise volume tables", "Composition charts", "PCU-adjusted summaries"], useCases: ["Traffic composition", "Freight studies", "Road planning"] },
  { slug: "mid-block-traffic-surveys", number: "03", title: "Mid-Block Traffic Surveys", category: "Road", icon: "Waypoints", summary: "Directional traffic volume and composition at a point along a road link, away from intersections.", deliverables: ["Directional and lane counts", "Vehicle classification profiles", "Speed summaries where supportable"], useCases: ["Link demand", "Capacity reviews", "Before-and-after studies"] },
  { slug: "traffic-volume-peak-hour-analysis", number: "04", title: "Traffic Volume & Peak-Hour Analysis", category: "Traffic", icon: "Chart", summary: "Peak-period identification, directional traffic volumes and Peak Hour Factor calculations.", deliverables: ["Interval and hourly tables", "Peak-period charts", "PHF calculations"], useCases: ["Capacity inputs", "Baseline surveys", "Demand profiles"] },
  { slug: "queue-length-analysis", number: "05", title: "Traffic Queue Length Analysis", category: "Intersection", icon: "List", summary: "Queue measurement at junctions, roundabouts, merge points and bottlenecks by cycle or interval.", deliverables: ["Maximum and average queues", "Approach and lane profiles", "Clearance summaries"], useCases: ["Signal optimisation", "Delay studies", "Operational reviews"] },
  { slug: "pedestrian-cyclist-nmu-counts", number: "06", title: "Pedestrian & Cyclist / NMU Counts", category: "Non-Motorized", icon: "Bike", summary: "Counts and movement analysis for pedestrians, cyclists and other non-motorized users.", deliverables: ["Counts by type and direction", "Crossing movement summaries", "Desire-line diagrams"], useCases: ["Active travel", "Crossing studies", "Public realm design"] },
  { slug: "origin-destination-analysis", number: "07", title: "Origin-Destination (OD) Analysis", category: "Journey", icon: "Map", summary: "Trip patterns between defined zones, with route-choice and journey-time analysis where included.", deliverables: ["Origin-destination matrices", "Route-choice summaries", "Journey-time analysis"], useCases: ["Through-traffic studies", "Network planning", "Route analysis"] },
  { slug: "parking-surveys", number: "08", title: "Parking Surveys", category: "Parking", icon: "Parking", summary: "Parking supply, demand, occupancy, duration, turnover and accumulation across time periods.", deliverables: ["Occupancy profiles", "Duration distributions", "Turnover summaries"], useCases: ["Parking strategy", "Development studies", "Kerbside management"] },
  { slug: "traffic-conflict-analysis", number: "09", title: "Traffic Conflict Analysis", category: "Safety", icon: "Shield", summary: "Structured examination of observed near-miss events and surrogate safety measures.", deliverables: ["Conflict event register", "TTC and PET where supportable", "Severity and location summaries"], useCases: ["Safety screening", "Behavioural studies", "Scheme reviews"] },
  { slug: "illegal-traffic-movement-analysis", number: "10", title: "Illegal Traffic Movement Analysis", category: "Safety", icon: "Ban", summary: "Observation of banned turns, wrong-way driving, no-entry violations and other prohibited movements.", deliverables: ["Events by type and interval", "Time-stamped references", "Movement diagrams"], useCases: ["Compliance studies", "Network safety", "Enforcement prioritisation"] },
  { slug: "red-light-violation-analysis", number: "11", title: "Red-Light Violation Analysis", category: "Safety", icon: "Traffic", summary: "Observation of vehicles entering after the signal changes to red when signal and stop line are visible.", deliverables: ["Violations by approach and class", "Time-into-red classification", "Event register and charts"], useCases: ["Signal safety", "Behaviour analysis", "Enforcement evidence"] },
  { slug: "saturation-flow-degree-of-saturation", number: "12", title: "Saturation Flow & Degree of Saturation (SAT/DOS)", category: "Intersection", icon: "Gauge", summary: "Estimates of maximum green-phase throughput and the proportion of capacity in use.", deliverables: ["Saturation-flow estimates", "DOS calculations", "Signal-cycle observations"], useCases: ["Capacity analysis", "Signal timing", "Junction modelling"] },
];

export const packages = [
  { name: "Essential Count", badge: "Foundation", summary: "Core traffic data for straightforward surveys.", includes: ["Volume counts", "Vehicle classification", "Direction or movement split", "Standard interval tables", "Summary workbook"], best: "Baseline counts and screening studies" },
  { name: "Intersection Performance", badge: "Most popular", summary: "Movement and queue evidence for junction analysis.", includes: ["Classified TMC", "Approach and exit summaries", "Queue observations", "Signal observations", "Project-ready charts"], best: "Operational reviews and modelling inputs", featured: true },
  { name: "Safety Review", badge: "Specialist", summary: "Structured observation of selected safety events.", includes: ["Selected safety events", "Time-stamped register", "Event classification", "Summary visualisations", "Evidence references"], best: "Safety screening and behavioural studies" },
  { name: "Complete Project", badge: "Bespoke", summary: "A tailored multi-service data package.", includes: ["Any of 12 services", "Multi-site analysis", "Integrated datasets", "Project report", "Named delivery contact"], best: "Corridors, programmes and complex projects", dark: true },
];
